# version: '3.5'

services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learn-nextjs
    ports: 
      - '3000:3000'
    volumes: 
      - .:/app
      - /app/node_modules