import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "./context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  weight: '400',
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Learn Next JS (edited)",
  description: "Generated by create next app",
  openGraph: {
    title: "Learn Next JS (edited)",
    description: "Generated by create next app",
    url: "mywebsite.com",
    siteName: "Learn Next JS",
    images: [
      {
        url:"/mywebsite.png",
        width: 1260,
        height: 800,
      }
    ],
    local:"en-EN",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable}`}>
        <AppWrapper>
          <header>This is the Root header</header>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
